name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  carousel_slider: ^4.2.1
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/slogan.png
    - assets/images/orderImage.png
    - assets/images/motorcycle.png
    - assets/images/bike.png
